### PR TITLE
Updated to support Theme

### PR DESCRIPTION
**Pull request by jasona**
Thanks for your work here! I needed the Theme support so I finished out the work there based on Xterm's spec for themes.

### CODE REVIEW

**Comment by BattlefieldDuck** [comment]
Thank you @jasona 🤗

Would you like to add the documentation base on https://github.com/xtermjs/xterm.js/blob/master/typings/xterm.d.ts#L274 ?

**Comment by jasona** [comment]
Oh, yes! Will do. I'm out of town until Tuesday but will update then!

**Comment by BattlefieldDuck** [comment]
I will do it for you😉.

**Comment by jasona** [comment]
You're awesome! Thank you!

**Comment by BattlefieldDuck** [comment]
v1.2.0 has been released, good luck with your projects!

**Pull request merged**
